// examples/web-eid-react-example/src/app/components/AuthGuard.tsx
// SPDX-FileCopyrightText: Estonian Information System Authority
// SPDX-License-Identifier: MIT
import { useContext, useEffect } from 'react'
import { AppContext } from '../context/AppContext'
import { useNavigate } from 'react-router'

export function AuthGuard({ children }: { children: React.ReactNode }) {
  const {
    state: {
      auth: { loggedIn }
    }
  } = useContext(AppContext)

  const navigate = useNavigate()

  useEffect(() => {
    if (loggedIn === false) {
      navigate('/')
    }
  }, [loggedIn, navigate])

  return <>{ loggedIn ? children : <div>Loading...</div> }</>
}

// examples/web-eid-angular-example/src/app/core/guards/auth.guard.ts
// SPDX-FileCopyrightText: Estonian Information System Authority
// SPDX-License-Identifier: MIT
import { inject } from '@angular/core';
import { CanActivateFn, Router } from '@angular/router';

import { AuthService } from '../services/auth.service';

export const authGuard: CanActivateFn = async (route, state) => {
  const authService = inject(AuthService);
  const router = inject(Router);

  const isLoggedIn = await authService.checkAuthState();

  return isLoggedIn ? true : router.createUrlTree(['/']);
};
